ALTER TABLE shifts ADD COLUMN IF NOT EXISTS expenses_amount NUMERIC(12,2) NOT NULL DEFAULT 0;
ALTER TABLE shifts ADD COLUMN IF NOT EXISTS expenses_note TEXT NOT NULL DEFAULT '';
ALTER TABLE shifts ADD COLUMN IF NOT EXISTS manque_amount NUMERIC(12,2) NOT NULL DEFAULT 0;
ALTER TABLE shifts ADD COLUMN IF NOT EXISTS manque_note TEXT NOT NULL DEFAULT '';
ALTER TABLE shifts ADD COLUMN IF NOT EXISTS staff_salary NUMERIC(12,2) NOT NULL DEFAULT 0;
ALTER TABLE shifts ADD COLUMN IF NOT EXISTS discrepancy_adjustment NUMERIC(12,2) NOT NULL DEFAULT 0;
